export interface Audio {
    id: number,
    file_resource_id: number,
    user_id: number,
    name: string,
    created_by_user: boolean,
    status: string,
    failure_reason: string,
    probe_json: string | Record<string, unknown>, 
    rms: number,
    peak: number,
    true_peak: number,
    lowpass_true_peak_15khz: number,
    loudness: number,
    dynamics: number,
    sharpness: number,
    space: number,
    loudness_range: number,
    drr: number,
    sound_quality: number,
    sound_quality2: number,
    dissonance: number,
    frames: number,
    sample_rate: number,
    channels: number,
    created_at: Date,
    updated_at: Date,
}